app/main.py, frontend/src/App.js, frontend/src/components/common/ErrorBoundary.js, frontend/src/components/common/LoggingTest.js, frontend/src/services/api/index.js, frontend/src/services/logger.js
feat: revamped centralized logging system with enhanced error handling and user action tracking
=> feat: revamped centralized logging system with enhanced error handling and user action tracking

app/api/deps.py, app/api/v1/endpoints/allergy.py, app/api/v1/endpoints/condition.py, app/api/v1/endpoints/encounter.py, app/api/v1/endpoints/immunization.py, app/api/v1/endpoints/lab_result.py, app/api/v1/endpoints/medication.py, app/api/v1/endpoints/procedure.py, app/api/v1/endpoints/treatment.py, app/api/v1/endpoints/vitals.py, app/core/config.py
This pull request introduces changes to enforce user-specific access controls across various endpoints in the application. The updates ensure that users can only access their own medical records by validating the `patient_id` associated with the authenticated user. The changes include the addition of helper functions for retrieving the current user's `patient_id` and verifying access to records, as well as updates to endpoint logic to incorporate these checks.
* [`app/api/deps.py`](diffhunk://#diff-a20068345295483bcc6bf6cdeb643eaed6fbddfdea25780683abfb492cbf37c1R187-R235): Added `get_current_user_patient_id` to retrieve the authenticated user's `patient_id` and `verify_patient_record_access` to validate record ownership. These functions centralize the logic for user-specific access …
=> Fix: Fixed the user-specific filtering for all the pages

app/api/v1/admin/dashboard.py, app/core/config.py, app/main.py, docker/Dockerfile
This pull request includes various updates and improvements across multiple files to enhance functionality, improve error handling, and ensure better routing and configuration. The changes primarily focus on the admin dashboard, API routing, and deployment configuration.
* Enhanced error logging in `safe_count` by adding detailed error messages and stack traces to improve debugging.
* Updated `safe_count` to include additional attribute checks for models like `User`, `Medication`, and `LabResult` to avoid potential attribute errors.
* Simplified and corrected recent activity logging by removing redundant entries and ensuring proper formatting.
* Added a test endpoint (`/stats-test`) for debugging routing issues in the admin dashboard.
* Improved handling of React SPA and API routes by …
=> Bug shared items fix

app/api/v1/endpoints/auth.py, app/crud/user.py, frontend/src/App.js, frontend/src/components/auth/ChangePasswordModal.css, frontend/src/components/auth/ChangePasswordModal.js, frontend/src/components/layout/Header.css, frontend/src/components/layout/Header.js, frontend/src/pages/Dashboard.js, frontend/src/pages/Settings.js, frontend/src/services/api/index.js, frontend/src/styles/pages/Dashboard.css, frontend/src/styles/pages/Settings.css
This pull request introduces a new "Change Password" feature and a dedicated "Settings" page to the application, along with associated backend, frontend, and styling updates. Below are the most important changes grouped by theme:
* Added a `change_password` endpoint in `auth.py` to allow users to update their passwords securely. It includes validation for the current password and new password requirements. (`[app/api/v1/endpoints/auth.pyR201-R278](diffhunk://#diff-58cbf6b3617b377d3a8851669ad55bc36905fa9a231e7c942e1d2470d2c5f091R201-R278)`)
* Introduced a new `update_password_by_user` method in `user.py` to handle password updates in the database, including hashing the new password. (`[app/crud/user.pyR178-R207](diffhunk://#diff-f049a7f666cb27ab2fa57ed01a691a24892ae80de316cef8e3d1c55dbd2aef …
=> Settings page

BACKUP_RESTORE_PLAN.md, app/api/deps.py, app/api/v1/endpoints/allergy.py, app/api/v1/endpoints/condition.py, app/api/v1/endpoints/encounter.py, app/api/v1/endpoints/immunization.py, app/api/v1/endpoints/lab_result.py, app/api/v1/endpoints/lab_result_file.py, app/api/v1/endpoints/medication.py, app/api/v1/endpoints/patients.py, app/api/v1/endpoints/procedure.py, app/api/v1/endpoints/treatment.py, app/api/v1/endpoints/vitals.py, app/core/config.py, app/core/database.py, app/crud/base.py, app/crud/lab_result.py, app/crud/lab_result_file.py, app/crud/vitals.py, app/main.py, app/models/models.py, frontend/src/contexts/AppDataContext.js, frontend/src/hooks/useGlobalData.js, frontend/src/pages/medical/Medication.js, frontend/src/pages/medical/Pharmacies.js
This pull request introduces a new dependency, `verify_patient_access`, to centralize and streamline patient access verification across multiple endpoints. It replaces redundant access checks with a reusable function, improving maintainability and reducing code duplication. Additionally, minor refactoring and logging enhancements were made.
* Added a new function `verify_patient_access` in `app/api/deps.py` to handle patient access verification. This function ensures that the current user has permissions to access the specified patient's records and raises a 404 error if access is denied.
* Replaced individual `patient_id` and `current_user_id` parameters with `patient_id: int = Depends(deps.verify_patient_access)` across various endpoints in the following files:
- …
=> Centralize patient access verification across endpoints

app/core/config.py, frontend/src/contexts/AppDataContext.js
This pull request includes updates to the app version and optimizations in the dependency arrays for memoized functions in the frontend's `AppDataProvider` component. The most significant changes include incrementing the app version and simplifying dependency arrays for better performance and maintainability.
* [`app/core/config.py`](diffhunk://#diff-46319cab8aa9cca75fe586084b86c07f241657d02b324944bb7d300ce560039bL18-R18): Updated the `VERSION` from `0.7.2` to `0.7.3`, indicating a minor release with potential bug fixes or small improvements.
* [`frontend/src/contexts/AppDataContext.js`](diffhunk://#diff-10633e74968521e48b7879363232a88bb6776c2fea5256f6207099f4af5a065eL216-R216): Simplified the dependency arrays in memoized functions by removing unnecessary dependencies (`isAuthenticated`, …
=> fix: fix excessive pharmacy api calls

frontend/src/pages/medical/Medication.js
This pull request updates the `Medication` component in `Medication.js` to streamline data fetching by replacing a broader fetch function with a more specific one. The changes focus on improving efficiency and clarity in the component's behavior.
Key changes:
* Replaced `fetchPatientAndMedications` with `fetchMedications` in the `resetForm` logic to narrow the scope of data fetching and avoid unnecessary API calls. (`[frontend/src/pages/medical/Medication.jsL250-R250](diffhunk://#diff-723d0680dbde6d738e4319f15341a6d9e438805afc6682cad1fb514ff578b0c8L250-R250)`)
* Updated the delete medication logic to use `fetchMedications` instead of `fetchPatientAndMedications`, ensuring only the relevant data is refreshed after a deletion. (`[frontend/src/pages/medical/Medication.jsL281-R281](diffhunk:// …
=> fix: corrected medication call

app/core/security.py, app/services/backup_service.py, app/services/restore_service.py, frontend/src/pages/admin/BackupManagement.js
This pull request introduces significant enhancements to the security and backup functionality of the application. Key changes include the addition of a centralized `SecurityValidator` class for validating database connections and backup paths, refactoring of backup operations to improve modularity and error handling, and the replacement of inline database connection parsing with reusable validation logic. These updates aim to improve maintainability, security, and reliability.
* Introduced the `SecurityValidator` class in `app/core/security.py` for centralized validation of database connection parameters (`validate_connection_params`) and backup paths (`validate_backup_path`). This includes hostname, username, and database name validation, as well as Docker-specific adjustments for …
=> refactor: replace custom SQL parsing with native PostgreSQL tools 

.gitattributes, README.md, app/scripts/README_BACKUP_CLI.md, app/scripts/USAGE_EXAMPLES.md, app/scripts/backup_cli.py, app/scripts/backup_db, app/scripts/backup_files, app/scripts/backup_full, app/scripts/restore, app/scripts/restore_cli.py, app/scripts/test_backup_cli.py, app/scripts/test_restore_cli.py, docker/Dockerfile
This pull request introduces significant updates to the repository, focusing on backup and restore functionality, configuration standardization, and documentation improvements. Key changes include the addition of `.gitattributes` for consistent file handling, enhancements to Docker Compose configurations for backup management, and comprehensive documentation for the backup CLI tools.
* Added a new `README_BACKUP_CLI.md` file documenting the usage of backup and restore CLI tools, including commands for database, file, and full system backups, as well as restore operations, safety features, and automation examples.
* Introduced a `USAGE_EXAMPLES.md` file providing practical examples for using the backup CLI, including cron job setups, advanced automation, and integration with external tools …
=> Backup CLI Support

frontend/.eslintrc.js, frontend/package.json, frontend/src/components/medical/VitalsChart.css, frontend/src/components/medical/VitalsChart.js, frontend/src/components/medical/VitalsForm.css, frontend/src/components/medical/VitalsForm.js, frontend/src/components/medical/VitalsList.js, frontend/src/pages/Dashboard.js, frontend/src/pages/medical/Vitals.css, frontend/src/pages/medical/Vitals.js
- Updated VitalsChart and VitalsForm components with modern styling and enhanced functionality.
- Refactored VitalsList to simplify rendering and improve performance.
- Enhanced Vitals page layout and added loading states for better user experience.
- Removed deprecated code and improved overall maintainability across medical components.
=> refactor: enhance Vitals components and styles 

.dockerignore, app/api/v1/api.py, app/api/v1/endpoints/system.py, app/core/datetime_utils.py, app/core/logging_config.py, app/core/logging_constants.py, app/core/uvicorn_logging.py, app/crud/base.py, app/main.py, docker/docker-compose.yml, docker/entrypoint.sh, frontend/src/services/frontendLogger.js, run.py
This pull request introduces comprehensive logging system enhancements to the Medical Records Management System, focusing on centralizing logging configuration, eliminating magic strings, and establishing a robust foundation for production-ready logging. Key changes include the creation of shared logging constants, enhanced CRUD operation logging, backend-frontend log level integration, and improved Uvicorn server logging consistency.
* **Created `app/core/logging_constants.py`** - A comprehensive centralized constants file that eliminates magic strings throughout the logging system. This module provides standardized field names (`LogFields` class), log level validation functions, sanitization utilities, and predefined message templates for consistent logging across the application.
* …
=> Logging v2

README.md, app/core/config.py, docker/.env.example, docker/Dockerfile, docker/docker-compose.yml, docker/entrypoint.sh, run.py
- Implemented SSL configuration in the FastAPI application, allowing for secure HTTPS connections.
- Updated `run.py` to conditionally enable SSL based on environment settings.
- Added SSL certificate and key file paths to the configuration in `config.py`.
- Modified Docker setup to include SSL environment variables and certificate mounting instructions.
- Enhanced entrypoint script to start the application with HTTPS if certificates are present, falling back to HTTP otherwise.
- Updated health check command in Docker to support both HTTP and HTTPS.
=> Add SSL support and configuration for FastAPI application

.dockerignore, .github/workflows/docker-image.yml, docker/Dockerfile, frontend/.npmrc
Adjusted the build file to improve container image build
=> Container improvments

frontend/src/contexts/AppDataContext.js
- Clear cache and fetch fresh patient data immediately upon user login.
- Update static list fetching to retrieve fresh data in parallel, improving data accuracy and user experience.
=> Enhance data fetching on user login in AppDataContext

.gitignore, frontend/src/services/api/index.js
removed excess slash for password change endpoint
=> fix: corrected API endpoint for password change

app/core/config.py, frontend/src/components/dashboard/InvitationNotifications.js, frontend/src/components/medical/PatientSelector.js, frontend/src/pages/Dashboard.js, frontend/src/pages/admin/DataModels.css, frontend/src/pages/admin/DataModels.js, frontend/src/pages/admin/ModelManagement.css
This pull request introduces theme-aware styling across multiple frontend components by integrating Mantine's `useMantineColorScheme` hook and replacing hardcoded CSS values with dynamic theme-based styles. It also standardizes CSS variables for better maintainability and consistency.
* **Dynamic Background and Border Colors**:
- Updated `InvitationNotifications`, `PatientSelector`, and `Dashboard` components to use `useMantineColorScheme` for dynamically setting background and border colors based on the active theme. [[1]](diffhunk://#diff-bc16e573f9041f7a07bcb161ecc62a951cdeec502e4101950d74aace6ca5af72L170-R178) [[2]](diffhunk://#diff-cef67f65458db4108931fb70c85ceb8c759e17c9c5e8b5290815939b636f6c7fL545-R554) [[3]](diffhunk://#diff-54ddf407d79f905218a487c36445b08c526431d74f0b5de582ccbb328 …
=> fix: updated remaining UI theming with color scheme support

frontend/src/pages/Dashboard.js
This pull request includes a small change to the `Dashboard.js` file. The change simplifies the logic for displaying the user's greeting by replacing the `currentActivePatient || user` condition with `authUser` and updating the displayed name to use `authUser` properties.
=> refactor: update greeting logic in Dashboard component

app/api/v1/endpoints/family_history_sharing.py, app/api/v1/endpoints/invitations.py, app/api/v1/endpoints/patients.py, app/core/__init__.py, app/core/config.py, app/core/logging_config.py, app/core/logging_middleware.py, app/scripts/setup-logrotate.sh, app/services/family_history_sharing.py, app/services/invitation_service.py, config/logrotate.conf, docker/Dockerfile, docs/LOG_ROTATION.md
This pull request introduces a comprehensive overhaul of the logging system, focusing on log rotation and configuration improvements, as well as cleanup of unused logging functionality. The changes include the addition of hybrid log rotation support, removal of unused log categories, and updates to ensure consistency across the codebase. Below are the most important changes grouped by theme:
* Introduced hybrid log rotation with support for both Linux `logrotate` and Python's built-in rotation. Added `_get_rotation_method` to dynamically select the rotation method (`logrotate` preferred in production). (`app/core/logging_config.py`) [[1]](diffhunk://#diff-7dd1be7f4d13e1cf6d9127a85bb052fd5978c6922140755f53667aa965f0c15dR43-R76) [[2]](diffhunk://#diff-7dd1be7f4d13e1cf6d9127a85bb052fd5978c692 …
=> Refactor: Update logging configuration across multiple modules

app/api/v1/admin/dashboard.py, app/core/startup.py, frontend/src/services/api/adminApi.js
This pull request refactors the recent activity tracking system in the admin dashboard API, simplifies the startup process, and enhances the frontend API service for better flexibility and backward compatibility. The most important changes include removing the legacy `get_recent_activity` endpoint, improving the enhanced activity logging endpoint, and updating the frontend service to support additional filters.
* Removed the legacy `get_recent_activity` endpoint, including its fallback logic for generating activity data from various tables. This simplifies the codebase by consolidating activity tracking into a single enhanced endpoint (`[app/api/v1/admin/dashboard.pyL156-L341](diffhunk://#diff-53bbc8c789fe172d0265527f888fece148476536a7635e93e34b5596a1092941L156-L341)`).
* Enhanced the …
=> Duplicate activities

app/core/config.py, frontend/src/pages/medical/Patient-Info.js
This pull request refactors the patient management logic in `Patient-Info.js` to use a new API module and introduces cache management to improve data consistency. Key changes include replacing API calls with methods from `patientApi`, integrating cache invalidation, and updating imports to support these changes.
* Replaced `apiService.createCurrentPatient` with `patientApi.createPatient` for creating patient records.
* Replaced `apiService.updateCurrentPatient` with `patientApi.updatePatient` for updating patient records, aligning with the new patient management system.
* Added `useCacheManager` hook to manage cache invalidation.
* Introduced `invalidatePatientList` and `invalidatePatient` calls to ensure data consistency across the app after patient data changes. …
=> Fix: Update patient  info page

frontend/src/services/frontendLogger.js, frontend/src/services/logger.js
This commit improves the security of session ID generation by adding a fallback mechanism. If `crypto.randomUUID()` is unavailable, it now uses `crypto.getRandomValues()` to generate a secure random value. An error is thrown if neither API is available, ensuring robust handling of session ID creation.
=> Enhance session ID generation in FrontendLogger and Logger classes

frontend/src/components/backup/ProgressNotification.js, frontend/src/hooks/useBackupNotifications.js, frontend/src/pages/admin/BackupManagement.js
This update introduces an enhanced notification system for backup management operations, replacing default success messages with a more robust notification handling approach. Key changes include:
- Integration of `useBackupNotifications` hook for managing notifications.
- Implementation of loading notifications during long-running actions (e.g., creating, uploading, and restoring backups).
- Improved error handling with user feedback for various backup actions.
- Refactoring of action execution to suppress default messages and utilize the new notification system.
These enhancements improve user experience by providing clearer feedback during backup operations.
=> Enhance Backup Management with Improved Notification System

frontend/src/App.js, frontend/src/config/activityConfig.js, frontend/src/contexts/AuthContext.js, frontend/src/hooks/ACTIVITY_TRACKING.md, frontend/src/hooks/index.js, frontend/src/hooks/useActivityTracker.js, frontend/src/hooks/useActivityTracker.test.js, frontend/src/services/apiClient.js, frontend/src/utils/secureActivityLogger.js, frontend/src/utils/throttleUtils.js
This pull request introduces a comprehensive activity tracking system to enhance session management, improve user experience, and strengthen security. Key changes include the addition of activity tracking hooks, integration with the `AuthContext` for session timeout handling, and configuration for tracking various user interactions. The changes also include robust error handling, performance optimizations, and secure logging.
* **Global Activity Tracking Component**: Added an `ActivityTracker` component in `App.js` to initialize global activity tracking, including mouse, keyboard, touch, and API activity tracking with error handling and performance monitoring. (`frontend/src/App.js`, [[1]](diffhunk://#diff-4e185b456927ee5c9781afdfbd5054b8cfb34c5b099a169c2bab8c822931625cR192-R275) …
=> feat: Implement Enhanced Activity Tracking System

frontend/src/pages/admin/ModelEdit.js
This update introduces additional safety checks when updating user models, specifically for username and role changes. Key changes include:
- Added confirmation prompts when an admin attempts to change their own username, warning about immediate logout.
- Implemented warnings for role changes that could result in loss of admin access, ensuring admins are aware of potential lockout scenarios.
- Updated validation logic to exclude password fields from validation during updates.
These enhancements improve the user experience by preventing accidental loss of access and ensuring informed decision-making during user updates.
=> feat: Enhance user model update process with safety checks

app/core/config.py, app/services/paperless_client.py, app/services/paperless_service.py, app/services/paperless_upload_manager.py, frontend/src/components/shared/DocumentManager.js, frontend/src/components/shared/DocumentManagerCore.js, frontend/src/components/shared/DocumentManagerWithProgress.js, frontend/src/components/shared/FileUploadZone.js, frontend/src/components/shared/FileUploadZone_OLD.js, frontend/src/components/shared/RenderModeContent.js, frontend/src/hooks/useUploadProgress.js
This pull request introduces robust handling for large document uploads to Paperless, focusing on preventing premature timeouts during lengthy processing. It adds smart timeout logic on the backend, extends upload timeouts, and updates the frontend to use the new upload flow for better reliability and user feedback.
**Backend improvements for upload reliability:**
* Added new configuration options in `app/core/config.py` for upload and processing timeouts, and status check intervals, making these values configurable via environment variables.
* Introduced `SmartPaperlessUploadManager` in `app/services/paperless_upload_manager.py` that monitors document processing status and only times out if there is no activity, reducing failed uploads for large or slow-processing files.
* Updated …
=> Bug: Document upload and timeout bugs

frontend/src/components/medical/conditions/ConditionFormWrapper.js, frontend/src/hooks/useApi.js, frontend/src/pages/medical/Conditions.js, frontend/src/services/api/index.js, frontend/src/utils/dateUtils.js, frontend/src/utils/errorUtils.js
This pull request introduces significant improvements to the medical condition form and its related API error handling. The main focus is on standardizing form input handling, enhancing date validation and formatting, and providing more user-friendly error messages for API validation errors. These changes improve both the user experience and code maintainability.
**Form handling and validation improvements:**
* Refactored `ConditionFormWrapper.js` to use a standardized `useFormHandlers` hook for all input changes, simplifying input management and reducing repetitive code. [[1]](diffhunk://#diff-1949427c84647adfa37181f8d83b564cdb1f629259017fa4ec3680dd21c4f037R16) [[2]](diffhunk://#diff-1949427c84647adfa37181f8d83b564cdb1f629259017fa4ec3680dd21c4f037R30-R40) …
=> Bug: Condition date pickers fix.

frontend/src/components/medical/family-history/FamilyHistoryCard.js, frontend/src/pages/medical/FamilyHistory.js
This pull request improves the robustness of event handling in the `FamilyHistoryCard` component and enhances error messaging in the `FamilyHistory` page. The main focus is to ensure that event handler functions can handle both direct calls and calls with an event object, preventing potential runtime errors, and to display more informative error messages to the user.
**Event handling improvements in `FamilyHistoryCard`:**
* Updated all event handler functions (`handleViewClick`, `handleEditClick`, `handleDeleteClick`, `handleAddConditionClick`, `handleEditConditionClick`, `handleDeleteConditionClick`, and `handleShareClick`) to safely check for the presence of an event object before calling `stopPropagation`, making the handlers more robust to different invocation contexts. …
=> Fix: Refactor event handling in FamilyHistoryCard

alembic/migrations/versions/20250821_0724_f32c3fa6d4a7_add_missing_performance_indexes.py, app/models/models.py
This pull request adds several database indexes to improve query performance, particularly for tables related to patients, medical records, and authentication. Indexes are introduced both through a new Alembic migration and directly in the SQLAlchemy ORM model definitions. These changes are aimed at speeding up common queries involving patient records, user lookups, and filtering by status or date.
Database indexing improvements:
* Added a new Alembic migration (`alembic/migrations/versions/20250821_0724_f32c3fa6d4a7_add_missing_performance_indexes.py`) that creates indexes on key columns in the `medications`, `lab_results`, `conditions`, `encounters`, `procedures`, `immunizations`, `allergies`, and `vitals` tables, as well as composite indexes for frequent query patterns and indexes for …
=> Add indexes to database for improved performance

app/api/v1/endpoints/entity_file.py, app/crud/__init__.py
This pull request significantly improves the security and authorization logic for entity file operations by enforcing strict access and ownership checks across all file-related endpoints. It introduces utility functions for entity lookup and ownership verification, replaces placeholder permission checks with robust implementations, and ensures that users can only access or modify files associated with patients they are authorized to view. Additionally, error handling and logging are enhanced for better traceability.
**Authorization and Access Control Improvements:**
* Introduced `get_entity_by_type_and_id` utility to fetch parent entities (like lab-result, procedure, insurance, encounter, or visit) by type and ID for use in authorization checks.
* Replaced all placeholder permission …
=> Enhance entity file handling with authorization checks

app/api/deps.py, frontend/src/contexts/AppContext.js, frontend/src/contexts/AuthContext.js, frontend/src/services/api/index.js
- Updated the HTTPBearer security scheme to allow custom error messages for missing credentials.
- Improved the `get_current_user` function to log and handle cases where no authentication credentials are provided.
- Refactored token management in the frontend to utilize secure storage for tokens, enhancing security.
- Added detailed logging for token verification and authentication errors to aid in debugging and monitoring.
- Implemented protocol detection for API URL to ensure secure connections in local development environments.
=> Enhance authentication and error handling in API and frontend components

app/core/config.py, frontend/src/App.js, frontend/src/components/medical/BaseMedicalForm.js, frontend/src/components/medical/MantineMedicalForm.js, frontend/src/pages/TestMedicationForm.js, frontend/src/pages/medical/Medication.js
This pull request introduces several improvements aimed at debugging and enhancing the performance and stability of the medication form, especially on small screens. The changes include the addition of a dedicated test page for the medication form, extensive performance logging, optimizations to prevent excessive re-renders, and improvements to responsive behavior. There are also minor updates, such as a version bump.
**Debugging Tools & Test Infrastructure:**
* Added a new `TestMedicationForm` page (`frontend/src/pages/TestMedicationForm.js`) with detailed performance metrics, test data, and logging to help debug form hangs and rendering issues on small screens. This page is accessible via the `/test/medication-form` route. [[1]](diffhunk://#diff-6711b71f3559a4a4664ea69075246b25c84a7d09fc …
=> Screen hang bug

app/api/v1/endpoints/practitioner.py, frontend/src/components/medical/BaseMedicalForm.js, frontend/src/components/medical/MantinePractitionerForm.js, frontend/src/components/medical/practitioners/PractitionerFormWrapper.js, frontend/src/config/medicalSpecialties.js, frontend/src/utils/medicalFormFields.js
This pull request introduces dynamic loading of medical specialties from the backend, improves the specialty selection UX with new Autocomplete and Combobox field types, and simplifies responsive logic in the `BaseMedicalForm`. It removes hardcoded specialty lists from the frontend and ensures that specialty options are always up-to-date and customizable by users.
**Dynamic Specialty Loading and Field Improvements:**
* Added a new backend API endpoint (`/specialties`) to fetch all unique medical specialties, enabling dynamic specialty lists in the frontend.
* Refactored both `MantinePractitionerForm` and `PractitionerFormWrapper` to fetch specialties dynamically using the new API, replacing hardcoded lists and adding robust loading/error handling. …
=> Improved practitioner specalties

frontend/src/components/adapters/FormSelect.js, frontend/src/components/adapters/Select.js, frontend/src/components/medical/BaseMedicalForm.js, frontend/src/components/medical/MantineMedicalForm.js, frontend/src/components/medical/medications/MedicationFormWrapper.js, frontend/src/hooks/useDebounce.js, frontend/src/hooks/useWindowDimensions.js, frontend/src/pages/Settings.js, frontend/src/pages/medical/Medication.js, frontend/src/services/api/index.js, frontend/src/services/api/paperlessApi.js, frontend/src/services/frontendLogger.js, frontend/src/services/logger.js, frontend/src/utils/performanceUtils.js
This pull request introduces performance optimizations and improved responsiveness across several form-related components, focusing on reducing unnecessary re-renders, optimizing dropdown behavior for large datasets, and enhancing mobile and tablet support. The main changes involve introducing `React.memo` and hooks like `useMemo` and `useCallback`, updating dropdown logic for better scalability, and refactoring the main medical form component for more efficient rendering and adaptive UI.
**Performance and Rendering Optimizations**
* Wrapped `FormSelect`, `Select`, `BaseMedicalForm`, and `MantineMedicalForm` components with `React.memo` and added custom comparison logic to `BaseMedicalForm` to prevent unnecessary re-renders, especially for large forms. Most event handlers and derived …
=> Bug; Small Screen hang during creation form

frontend/src/components/adapters/Select.js, frontend/src/components/medical/BaseMedicalForm.js, frontend/src/hooks/useScrollThrottle.js, frontend/src/hooks/useWindowDimensions.js, frontend/src/index.css, frontend/src/services/performanceMonitor.js, frontend/src/styles/dropdown-performance.css
This pull request introduces significant performance optimizations and responsive behavior improvements to the `Select` component and its usage in the `BaseMedicalForm`. The changes focus on making dropdowns and select fields more efficient, especially for large datasets and constrained viewports, while adding robust monitoring and emergency fallback mechanisms to prevent UI freezes or render loops.
* The `Select` component now aggressively limits the number of rendered options based on dataset size, disables expensive features (like search and clearable) in minimal performance modes, and adapts dropdown rendering for narrow screens and constrained viewports. It also logs frequent option changes for debugging. (`frontend/src/components/adapters/Select.js`) …
=> More small screen fixes

frontend/src/adapters/MantineResponsiveAdapter.js, frontend/src/components/medical/MedicalFormModal.js, frontend/src/components/shared/MedicalTable.js, frontend/src/components/ui/DashboardCard.js, frontend/src/factories/ResponsiveComponentFactory.js, frontend/src/hoc/withResponsive.js, frontend/src/hoc/withResponsiveProps.js, frontend/src/strategies/GridLayoutStrategy.js, frontend/src/strategies/LayoutStrategy.js
Implements comprehensive component enhancement layer with responsive capabilities, factory patterns, and Mantine UI integration. This PR establishes the foundation for creating responsive components with consistent behavior across breakpoints.
- **Higher-Order Components (HOCs)** for component enhancement with responsive props and styling
- **ResponsiveComponentFactory** with multiple creation patterns (basic, advanced, Mantine-optimized)
- **MantineResponsiveAdapter** for seamless integration with Mantine UI components
- **Strategy Pattern** implementation for flexible layout calculations (Grid, Form, Table optimizations)
- **Enhanced Components**: DashboardCard, MedicalTable, MedicalFormModal with responsive behavior
- React hooks compliance with proper memoization and performance …
=>  feat: Add responsive component enhancement infrastructure (#2)

app/api/v1/endpoints/custom_reports.py, app/core/config.py, app/services/custom_report_service.py, app/services/export_service.py, frontend/src/hooks/useCustomReports.js, frontend/src/pages/reports/ReportBuilder.js, frontend/src/services/api/index.js
This pull request introduces significant improvements to how patient selection is handled across backend services and enhances logging for better traceability. The main change is that all data summary and export operations now consistently use the user's active patient, which fixes issues when users have multiple patients and ensures accurate data retrieval. Additionally, logging has been upgraded throughout the backend and frontend to provide more useful information for debugging and monitoring.
**Backend: Patient Selection and Logging Improvements**
* Updated data summary and export logic to use the user's `active_patient_id` instead of assuming a single patient per user, ensuring correct data is retrieved for the selected patient. This change affects `CustomReportService` and …
=> Custom report bug

app/services/custom_report_service.py
This pull request updates the logic for patient record access and selection in the custom report service, ensuring that users interact only with their currently active patient profile. The changes add stricter validation for user and patient existence, and update how patient information is retrieved for report generation.
**Record ownership and validation improvements:**
* In `validate_record_ownership`, the code now retrieves the user by `user_id`, checks for existence, and ensures that an `active_patient_id` is set before fetching the patient record. More specific permission errors are raised for missing user or active patient selection.
**Patient selection logic in report generation:**
* In `generate_selective_report`, patient information is now retrieved using the user's …
=> fix: Update custom report validation to use active patient

app/api/v1/endpoints/users.py, app/core/config.py, app/core/constants.py, app/models/models.py, app/services/user_deletion_service.py
This pull request refactors the user deletion flow to improve safety, maintainability, and transactional integrity. The core logic for deleting a user and all associated data has been moved into a new `UserDeletionService`, which handles validation, cascading deletes, and logging. The API endpoint now uses this service, and the database relationships have been updated to ensure proper cascade deletion of user preferences.
* Introduced a new `UserDeletionService` (`app/services/user_deletion_service.py`) that encapsulates all validation and deletion logic for user accounts, including handling associated records and transactional safety.
* The `delete_current_user_account` endpoint in `users.py` now delegates deletion to the service, removing duplicated logic, improving error handling, and …
=> refactor: Enhance user account deletion process with dedicated service

frontend/src/App.js, frontend/src/pages/auth/Login.js, frontend/src/pages/auth/UserCreation.js, frontend/src/styles/pages/Login.css
This pull request refactors the user account creation flow in the frontend. Instead of handling user registration within the `Login` page via a modal, it introduces a dedicated `UserCreation` page for a clearer and more maintainable user experience. Related logic and styles for the modal are removed, and navigation is updated accordingly.
**User Account Creation Flow Refactor**
* Added a new `UserCreation` page (`frontend/src/pages/auth/UserCreation.js`) that provides a standalone route and form for user registration, with improved UI and automatic login after account creation.
* Updated routing in `frontend/src/App.js` to include the new `/user-creation` route and component. [[1]](diffhunk://#diff-4e185b456927ee5c9781afdfbd5054b8cfb34c5b099a169c2bab8c822931625cR40) …
=> feat: Add user creation page and refactor login component

app/core/config.py, app/services/user_deletion_service.py
This pull request focuses on improving the user account deletion workflow to address circular dependency issues related to the `active_patient_id` field and ensure data integrity during deletion. The changes update the application version and introduce safeguards when deleting patient and user records.
* Before deleting a patient record, the code now nullifies any `active_patient_id` references in the `User` table that point to the patient being deleted, preventing circular dependency issues. (`app/services/user_deletion_service.py`, [app/services/user_deletion_service.pyR147-R163](diffhunk://#diff-0347f16bb7f88a1e9ae1baa6b2fa97b99ec66b744d3ffbb8bd01b5b27fb3923dR147-R163))
* After nullifying references and updating related activity logs, the patient record is deleted, and changes are …
=> fix: Account deletion circular dependency 

app/models/enums.py, frontend/src/components/common/SearchResults.js, scripts/populate_test_data.py
- Updated MedicationStatus enum to replace 'inactive' with 'stopped' for better alignment with terminology.
- Added 'unconfirmed' status to AllergyStatus enum for comprehensive allergy tracking.
- Refined SeverityLevel enum by renaming 'critical' to 'life-threatening' for clarity.
- Standardized test category and type values in populate_test_data.py to lowercase for consistency.
- Updated lab results descriptions in test data to use more precise terminology, enhancing data quality.
=> fix: fixed dashboard search bar

.github/workflows/docker-image.yml, README.md, app/core/config.py, docker/Dockerfile, docker/README_SSO.md, docker/docker-compose.yml, docker/entrypoint.sh, docker/unraid-template.xml, docs/SSO_QUICK_START.md, docs/SSO_SETUP_GUIDE.md, frontend/.env, frontend/.env.production, frontend/public/index.html, frontend/public/manifest.json, frontend/src/components/auth/ProfileCompletionModal.js, frontend/src/pages/Dashboard.js, frontend/src/pages/ExportPage.js, frontend/src/pages/auth/Login.js, frontend/src/pages/auth/UserCreation.js, frontend/src/pages/medical/Patient-Info.js, run.py
This pull request performs a comprehensive rebranding of the project from "Medical Records Management System" (or "Personal-Medical-Records-Keeper") to "MediKeep". The changes affect nearly all aspects of the repository, including documentation, Docker configuration, environment variables, and application metadata. The update ensures consistency in naming, image references, and configuration across the codebase and deployment artifacts.
**Project-wide rebranding and naming updates:**
* Changed all references in documentation, code, Dockerfiles, and configuration from "Medical Records" or "Personal-Medical-Records-Keeper" to "MediKeep", including project name, app name, and descriptions. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L1-R17) …
=> Renaming to MediKeep!

app/api/v1/endpoints/search.py, frontend/src/App.js, frontend/src/components/common/GlobalSearch.js, frontend/src/components/common/SearchResults.js, frontend/src/pages/Dashboard.js, frontend/src/pages/SearchResults.js, frontend/src/services/api/index.js, frontend/src/services/searchService.js
This pull request updates the backend search endpoint and the frontend search experience to improve search accuracy, consistency, and user navigation. Major changes include improved search query logic, updates to model field mappings, and enhancements to the frontend search UI, including a new "See All" results page and more robust logging.
**Backend Search Improvements**
* Updated search queries to use `ilike` on tags for case-insensitive and partial matching, improving tag search accuracy across all record types. [[1]](diffhunk://#diff-32fe9bd8e8051b8609d74f8acdcb8367125f7edc1a61902e5ba0370ae2134c82L143-R155) [[2]](diffhunk://#diff-32fe9bd8e8051b8609d74f8acdcb8367125f7edc1a61902e5ba0370ae2134c82L186-R188) [[3]](diffhunk://#diff-32fe9bd8e8051b8609d74f8acdcb8367125f7edc1a61902e5ba0370ae213 …
=> Swap to api for global search and add search results page

app/services/custom_report_pdf_generator.py
This pull request updates the `CustomReportPDFGenerator` service to support Unicode-compatible fonts, improving international character support in generated PDFs. The changes introduce dynamic font registration for both normal and bold text, falling back to standard fonts if needed. All styles and table formatting now use these dynamically registered fonts, ensuring consistent and correct rendering for a wider range of languages and symbols.
Font registration and internationalization:
* Added `_register_fonts` method to dynamically register Unicode-compatible fonts (DejaVu Sans or Arial) for normal and bold text, with OS-specific font path searching and fallback to Helvetica if none are found. (`app/services/custom_report_pdf_generator.py`)
* Updated the constructor of …
=> feat: enhance PDF generation with Unicode font support

frontend/src/App.css, frontend/src/App.js, frontend/src/components/layouts/ResponsiveLayout.css, frontend/src/components/layouts/ResponsiveLayout.js, frontend/src/components/shared/Footer.tsx
This pull request introduces a shared footer component to the application and ensures it appears consistently across all pages. The changes include updates to the layout and styling to support the new footer, as well as the addition of the actual `Footer` component.
**UI and Layout Enhancements:**
* Added a new `Footer` component in `frontend/src/components/shared/Footer.tsx`, displaying copyright information and a GitHub link.
* Updated `frontend/src/App.js` to import and render the `Footer` component at the bottom of the main layout, ensuring it appears on every page. [[1]](diffhunk://#diff-4e185b456927ee5c9781afdfbd5054b8cfb34c5b099a169c2bab8c822931625cR79) [[2]](diffhunk://#diff-4e185b456927ee5c9781afdfbd5054b8cfb34c5b099a169c2bab8c822931625cR589-R592)
* Modified the main `.App` …
=> feat: added page footer
